---
#
# Install packages
#

- name: Install packages
  package: name={{ item }} state=present
  with_items: "{{ packages }}"

- name: Set JAVA_HOME  
  lineinfile: dest="/root/.bashrc" regexp="^export JAVA\_HOME=" line="export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-armhf/jre"

- name: Set PATH
  lineinfile: dest="/root/.bashrc" regexp="^export PATH=" line="export PATH=${PATH}:${JAVA_HOME}/bin"

- name: Install package doxygen
  package: name=doxygen state=present
  
- name: Check if tinyb is already cloned
  stat: path="{{ ansible_env.HOME }}/tinyb/.git"
  register: tinyb_git_repo
  
- name: Set tiny_home
  set_fact: tiny_home="{{ ansible_env.HOME }}/tinyb"

- name: Clone tinyb into home directory
  git: repo=https://github.com/intel-iot-devkit/tinyb.git
       dest={{ tiny_home }}
       version={{ tinyb_sha1 }}
  when: not tinyb_git_repo.stat.exists
  
- file: path={{ tiny_home }}/build state=directory mode=755