---
#
# Install packages
#

- name: Install packages
  package: name={{ item }} state=present
  with_items: "{{ packages }}"

- name: Set JAVA_HOME  
  lineinfile: dest="/root/.bashrc" regexp="^JAVA\_HOME=" line="export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-armhf/jre"

- name: Set PATH
  lineinfile: dest="/root/.bashrc" regexp="^PATH=" line="export PATH=${PATH}:${JAVA_HOME}/bin"


